name: Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Render Deploy
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d6dovu24d50c73b0dibg?key=vlESCMHJvSk"

      - name: Wait for Render auto-deploy
        run: sleep 5
